version: "3.8"
services:
  libsql-server:
    image: libsql/server:v0.24.0
    ports:
      - "8080:8080"
    volumes:
      - libsql-data:/data

  minio:
    image: minio/minio:RELEASE.2024-02-16T01-53-20Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: recollection
      MINIO_ROOT_PASSWORD: strongpassword
    volumes:
      - minio-data:/data

  recollection:
    build: .
    ports:
      - "8000:8000"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    environment:
      - LIBSQL_URL=http://libsql-server:8080
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=recollection
      - MINIO_SECRET_KEY=strongpassword

volumes:
  libsql-data:
  minio-data:
